# Generated by Django 5.0.3 on 2024-03-22 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='coaches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coachname', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('age', models.CharField(max_length=200)),
                ('event', models.CharField(max_length=200)),
                ('qualification', models.FileField(upload_to='certificates')),
                ('gender', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='chusers')),
                ('password', models.CharField(max_length=200)),
            ],
        ),
    ]
