# Generated by Django 5.0.3 on 2024-03-26 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_coaches'),
    ]

    operations = [
        migrations.CreateModel(
            name='instituitions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instituitionname', models.CharField(max_length=200)),
                ('supervisername', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('event', models.CharField(max_length=200)),
                ('icertificate', models.FileField(upload_to='instncertificates')),
                ('location', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='instn')),
                ('password', models.CharField(max_length=200)),
            ],
        ),
    ]
