# Generated by Django 5.0.3 on 2024-03-26 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_instituitions'),
    ]

    operations = [
        migrations.CreateModel(
            name='shops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopname', models.CharField(max_length=200)),
                ('supervisername', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('shopcertificate', models.FileField(upload_to='shpcertificates')),
                ('location', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='shp')),
                ('password', models.CharField(max_length=200)),
            ],
        ),
    ]
