# Generated by Django 5.0.3 on 2024-05-17 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=200)),
                ('brandname', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('shopname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.shops')),
            ],
        ),
    ]
